### ISSUE TITLE
ambiguous relation when relating to prometheus - missing docs

### ISSUE THREAD

**Issue by samuelallan72** [canonical/prometheus-scrape-config-k8s-operator#35]
### Bug Description

If I follow the instructions in the readme:

> Relate the charms together.
> 
> ```
> $ juju relate cassandra-k8s scrape-interval-config
> $ juju relate scrape-interval-config prometheus-k8s
> ```

I get an error:

```
ubuntu@server:~$ juju relate scrape-interval-config prometheus
ERROR ambiguous relation: "scrape-interval-config prometheus" could refer to "prometheus:metrics-endpoint scrape-interval-config:metrics-endpoint"; "scrape-interval-config:configurable-scrape-jobs prometheus:self-metrics-endpoint"
```

The readme must be updated, and it should be documented what the use cases are for each endpoint.

### To Reproduce

see above

### Environment

latest/stable or latest/edge charm (same error)

### Relevant log output

see above

**Comment by lucabello** [comment]
Clsoed by https://github.com/canonical/prometheus-scrape-config-k8s-operator/pull/51
