### ISSUE TITLE
The diagram in INTEGRATING.md is impossible.

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-scrape-config-k8s-operator#42]
### Bug Description

The diagram in INTEGRATING.md is impossible. The relations don't work that way.

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

**Comment by PietroPasotti** [comment]
![image](https://github.com/canonical/prometheus-scrape-config-k8s-operator/assets/6230162/ded8e30e-1e56-4288-b999-fa8b2e3662d6)

issue is the lower lxd deployment box is incorrect: you can't put scrape config between grafana-agent (machine charm) and prometheus, because it's a prometheus_scrape.
